export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const SET_MESSAGE = "SET_MESSAGE"
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const FETCH_ALL_MEMBERS = "FETCH_ALL_MEMBERS"
export const FETCH_ALL_MEMBERS_SUCCESS = "FETCH_ALL_MEMBERS_SUCCESS"
export const FETCH_ALL_MEMBERS_FAILURE = "FETCH_ALL_MEMBERS_FAILURE"
export const FETCH_ALL_EMPLOYEES = "FETCH_ALL_EMPLOYEES"
export const FETCH_ALL_EMPLOYEES_SUCCESS = "FETCH_ALL_EMPLOYEES_SUCCESS"
export const FETCH_ALL_EMPLOYEES_FAILURE = "FETCH_ALL_EMPLOYEES_FAILURE"

export const CHANGE_MEMBER_ROLE = "CHANGE_MEMBER_ROLE"
export const MODIFY_EMPLOYEE_DATA = "MODIFY_EMPLOYEE_DATA"

export const DELETE_MEMBER = "DELETE_MEMBER"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"

