export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const SET_MESSAGE = "SET_MESSAGE"
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const FETCH_ALL_MEMBERS = "FETCH_ALL_MEMBERS"
export const FETCH_ALL_MEMBERS_SUCCESS = "FETCH_ALL_MEMBERS_SUCCESS"
export const FETCH_ALL_MEMBERS_FAILURE = "FETCH_ALL_MEMBERS_FAILURE"
export const FETCH_ALL_EMPLOYEES = "FETCH_ALL_EMPLOYEES"
export const FETCH_ALL_EMPLOYEES_SUCCESS = "FETCH_ALL_EMPLOYEES_SUCCESS"
export const FETCH_ALL_EMPLOYEES_FAILURE = "FETCH_ALL_EMPLOYEES_FAILURE"
export const FETCH_ALL_INGREDIENTS_SUCCESS = "FETCH_ALL_INGREDIENTS_SUCCESS"
export const FETCH_ALL_RECIPES_SUCCESS = "FETCH_ALL_RECIPES_SUCCESS"
export const FETCH_RECIPE_IMAGES_SUCCESS = "FETCH_RECIPE_IMAGES_SUCCESS"

export const ADD_INGREDIENT_SUCCESS = "ADD_INGREDIENT_SUCCESS"

export const CHANGE_MEMBER_ROLE = "CHANGE_MEMBER_ROLE"
export const CHANGE_EMPLOYEE_ROLE = "CHANGE_EMPLOYEE_ROLE"
export const MODIFY_EMPLOYEE_DATA = "MODIFY_EMPLOYEE_DATA"

export const RESET_PWD = "RESET_PWD"

export const DELETE_MEMBER = "DELETE_MEMBER"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const DELETE_INGREDIENT_SUCCESS = "DELETE_INGREDIENT_SUCCESS"
export const DELETE_RECIPES_SUCCESS = "DELETE_RECIPES_SUCCESS"

