export const memberData = [
  {
    account: "ye1",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "member",
  },
  {
    account: "abcs",
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc33",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "vip",
  },
  {
    account: "qqqq",
    username: "zhen",
    email: "dd@djl.com",
    phone: "09388737",
    role: "vip",
  },
  {
    account: "yayaya",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "vip",
  },
  {
    account: "ye12",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "member",
  },
  {
    account: "abcs2",
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc332",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "vip",
  },
  {
    account: "qqqq2",
    username: "zhen",
    email: "dd@djl.com",
    phone: "09388737",
    role: "vip",
  },
  {
    account: "yayaya2",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "vip",
  },
  {
    account: "ye13",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "member",
  },
  {
    account: "abcs3",
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc333",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "vip",
  },
  {
    account: "qqqq3",
    username: "zhen",
    email: "dd@djl.com",
    phone: "09388737",
    role: "vip",
  },
  {
    account: "yayaya3",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "vip",
  },
  {
    account: "ye144",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "member",
  },
  {
    account: "abcs4",
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc334",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "vip",
  },
  {
    account: "qqqq4",
    username: "zhen",
    email: "dd@djl.com",
    phone: "09388737",
    role: "vip",
  },
  {
    account: "yayaya4",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "vip",
  },
  {
    account: "ye15",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "member",
  },
  {
    account: "abcs5",
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc335",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "vip",
  },
  {
    account: "qqqq5",
    username: "zhen",
    email: "dd@djl.com",
    phone: "09388737",
    role: "vip",
  },
  {
    account: "yayaya5",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "vip",
  },
  {
    account: "ye16",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "member",
  },
  {
    account: "abcs6",
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc336",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "vip",
  },
  {
    account: "qqqq6",
    username: "zhen",
    email: "dd@djl.com",
    phone: "09388737",
    role: "vip",
  },
  {
    account: "yoyoyoy6",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "vip",
  },
]
