export const memberData = [
  {
    account: "ye1",
    username: "yu",
    email: "djfs@djk.com",
    id: 1,
    phone: "09373652",
    role: "MEMBER",
  },
  {
    account: "abcs",
    username: "amy",
    email: "abck@fdjask.co",
    id: 13,
    phone: "3",
    role: "4",
  },
  {
    account: "abc33",
    username: "shannon",
    id: 133,
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "VIP",
  },
  {
    account: "qqqq",
    username: "zhen",
    id: 1333,
    email: "dd@djl.com",
    phone: "09388737",
    role: "VIP",
  },
  {
    account: "yayaya",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "VIP",
    id: 13333,
  },
  {
    account: "ye12",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "MEMBER",
    id: 133333,
  },
  {
    account: "abcs2",
    username: "amy",
    id: 12,
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc332",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    id: 122,
    role: "VIP",
  },
  {
    account: "qqqq2",
    username: "zhen",
    email: "dd@djl.com",
    id: 1222,
    phone: "09388737",
    role: "VIP",
  },
  {
    account: "yayaya2",
    username: "dena",
    id: 12222,
    email: "dd@com.com",
    phone: "03636363",
    role: "VIP",
  },
  {
    account: "ye13",
    id: 1111,
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "MEMBER",
  },
  {
    account: "abcs3",
    username: "amy",
    email: "abck@fdjask.co",
    id: 111,
    phone: "3",
    role: "4",
  },
  {
    account: "abc333",
    username: "shannon",
    id: 111111,
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "VIP",
  },
  {
    account: "qqqq3",
    username: "zhen",
    email: "dd@djl.com",
    id: 14,
    phone: "09388737",
    role: "VIP",
  },
  {
    account: "yayaya3",
    username: "dena",
    id: 144,
    email: "dd@com.com",
    phone: "03636363",
    role: "VIP",
  },
  {
    account: "ye144",
    username: "yu",
    email: "djfs@djk.com",
    id: 441,
    phone: "09373652",
    role: "MEMBER",
  },
  {
    account: "abcs4",
    id: 414,
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc334",
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    id: 14444,
    role: "VIP",
  },
  {
    account: "qqqq4",
    username: "zhen",
    id: 551,
    email: "dd@djl.com",
    phone: "09388737",
    role: "VIP",
  },
  {
    account: "yayaya4",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    id: 51,
    role: "VIP",
  },
  {
    account: "ye15",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    id: 155,
    role: "MEMBER",
  },
  {
    account: "abcs5",
    username: "amy",
    email: "abck@fdjask.co",
    phone: "3",
    id: 1555,
    role: "4",
  },
  {
    account: "abc335",
    id: 15555,
    username: "shannon",
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "VIP",
  },
  {
    account: "qqqq5",
    username: "zhen",
    email: "dd@djl.com",
    id: 1435,
    phone: "09388737",
    role: "VIP",
  },
  {
    account: "yayaya5",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    id: 143,
    role: "VIP",
  },
  {
    account: "ye16",
    username: "yu",
    email: "djfs@djk.com",
    phone: "09373652",
    role: "MEMBER",
    id: 132,
  },
  {
    account: "abcs6",
    username: "amy",
    id: 121,
    email: "abck@fdjask.co",
    phone: "3",
    role: "4",
  },
  {
    account: "abc336",
    username: "shannon",
    id: 13232,
    email: "fjjf@djo.com",
    phone: "32323232",
    role: "VIP",
  },
  {
    account: "qqqq6",
    id: 154,
    username: "zhen",
    email: "dd@djl.com",
    phone: "09388737",
    role: "VIP",
  },
  {
    id: 165,
    account: "yoyoyoy6",
    username: "dena",
    email: "dd@com.com",
    phone: "03636363",
    role: "VIP",
  },
]















export const employeeData = [
  {
    id: 1,
    account: "admin",
    email: "email",
    username: "Hung",
    department: "Sales",
    title: "4",
    phone: "09782332",
    role: "ADMIN",
  },
  {
    id: 2,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "王慧d婷",
    department: "FoodManagement",
    title: "4",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 3,
    account: "edfswewew",
    email: "amy@gafdsmil.com",
    username: "dena",
    department: "CenterKitchen",
    title: "3",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 4,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "amy",
    department: "CenterKitchen",
    title: "3",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 5,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "shannon",
    department: "FoodManagement",
    title: "3",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 6,
    account: "ewewew3232",
    email: "amy@gamil.com",
    username: "amy",
    department: "EmployeeManagement",
    title: "3",
    phone: "09002932329309",
    role: "MANAGER",
  },
  {
    id: 7,
    account: "ewewew",
    email: "hello@gamil.com",
    username: "hello",
    department: "DeliveryManagement",
    title: "2",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 12,
    account: "admin",
    email: "email",
    username: "Hung",
    department: "Sales",
    title: "2",
    phone: "09782332",
    role: "ADMIN",
  },
  {
    id: 22,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "王慧d婷",
    department: "FoodManagement",
    title: "2",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 32,
    account: "edfswewew",
    email: "amy@gafdsmil.com",
    username: "dena",
    department: "CenterKitchen",
    title: "2",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 42,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "amy",
    department: "CenterKitchen",
    title: "2",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 52,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "shannon",
    department: "FoodManagement",
    title: "2",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 62,
    account: "ewewew3232",
    email: "amy@gamil.com",
    username: "amy",
    department: "EmployeeManagement",
    title: "1",
    phone: "09002932329309",
    role: "MANAGER",
  },
  {
    id: 72,
    account: "ewewew",
    email: "hello@gamil.com",
    username: "hello",
    department: "DeliveryManagement",
    title: "1",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 13,
    account: "admin",
    email: "email",
    username: "Hung",
    department: "Sales",
    title: "2",
    phone: "09782332",
    role: "ADMIN",
  },
  {
    id: 23,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "王慧d婷",
    department: "FoodManagement",
    title: "4",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 33,
    account: "edfswewew",
    email: "amy@gafdsmil.com",
    username: "deeena",
    department: "CenterKitchen",
    title: "4",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 43,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "amy",
    department: "CenterKitchen",
    title: "1",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 53,
    account: "ewewew",
    email: "amy@gamil.com",
    username: "shannon",
    department: "FoodManagement",
    title: "1",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
  {
    id: 63,
    account: "ewewew3232",
    email: "amy@gamil.com",
    username: "amy",
    department: "EmployeeManagement",
    title: "1",
    phone: "09002932329309",
    role: "MANAGER",
  },
  {
    id: 73,
    account: "ewewew",
    email: "hello@gamil.com",
    username: "hello",
    department: "DeliveryManagement",
    title: "1",
    phone: "0900299309",
    role: "EMPLOYEE",
  },
]